tasks:
  - name: Install AWS CLI
    init: |
      cd $GITPOD_REPO_ROOT
      curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
      unzip awscliv2.zip
      # Install using parameters to ensure /usr/local/bin symlink is created
      sudo ./aws/install --bin-dir /usr/local/bin --install-dir /usr/local/aws-cli
      
      # OPTIONAL: Test to see if it's available after installation
      aws --version
vscode:
  extensions: 
    - 42Crunch.vscode-openapi